### PR TITLE
Add support for the ESP32-C6 and ESP32-H2

### LINKED ISSUE #12: Add support for the ESP32-C6

### LINKED ISSUE #13: Add support for the ESP32-H2

### PR DESCRIPTION
**Pull request by jessebraham**
Keeping this as a draft until `esp-println` has a new release, but the work is otherwise done. I added some comments for the features and updated our build script to match `esp-println` as well.

Closes #12 
Closes #13

### CODE REVIEW

**Review by bjoernQ — APPROVED** [review]
LGTM

**Comment by jessebraham** [comment]
Confirmed working for the C6, haven't written the linker scripts for the H2 yet so haven't tested it.

**Comment by jessebraham** [comment]
Confirmed working for the C6.

**Comment by jessebraham** [comment]
Gonna split this up so we can publish a release with C6 support.

**Pull request closed without merging**
